'use client'

import { motion } from 'framer-motion'
import { Zap, TrendingDown, Gauge, Bell, IndianRupee } from 'lucide-react'
import { Card, CardContent } from '@/components/ui/card'
import { Skeleton } from '@/components/ui/skeleton'
import { KpiCard } from '@/components/dashboard/kpi-card'
import { MiniTrendChart } from '@/components/dashboard/mini-trend-chart'
import { PeakUsageSummary } from '@/components/dashboard/peak-usage-summary'
import { AlertsPreview } from '@/components/dashboard/alerts-preview'
import { RecommendationsPreview } from '@/components/dashboard/recommendations-preview'
import { EnergyReadings } from '@/components/dashboard/energy-readings'
import { useDashboardSummary, useImpact } from '@/hooks/use-energy-data'
